---
show-prefix: false
show-messages-onjoin: false
force-hub: false
enable-hub-message: true
hub-message: Welcome to DarkRealms {PLAYER}
force-spawn: false
enable-spawn-message: false
spawn-message: Teleported To {WORLD} Spawn
enable-aliases: true
...
